"""
Train Knowledge Graph with AI-Generated Data
"""

import json
from train_knowledge_graph import KnowledgeGraphTrainer


def main():
    """Train with AI-generated data"""
    print("="*80)
    print("TRAINING WITH AI-GENERATED DATA")
    print("="*80)
    
    # Check if AI data exists
    ai_data_file = "ai_training_data/ai_generated_training.json"
    
    try:
        # Load AI data to check
        with open(ai_data_file, 'r') as f:
            data = json.load(f)
        
        print(f"\n✅ Found AI-generated training data:")
        print(f"   • Examples: {data['metadata']['total_examples']}")
        print(f"   • Generated by: {data['metadata']['generated_by'].upper()}")
        print(f"   • Model: {data['metadata']['model']}")
        
        # Initialize trainer
        print(f"\n🚀 Initializing trainer...")
        trainer = KnowledgeGraphTrainer()
        
        # Train
        trainer.train_from_file(ai_data_file)
        
        # Save
        output_file = trainer.save_trained_graph("ai_trained_knowledge_graph.json")
        
        # Test
        trainer.test_trained_graph()
        
        print(f"\n{'='*80}")
        print("✅ TRAINING COMPLETE WITH AI DATA!")
        print('='*80)
        print(f"\n📁 Trained graph: {output_file}")
        print(f"\n📊 Training Results:")
        print(f"   • {trainer.training_stats['examples_loaded']} examples processed")
        print(f"   • {trainer.training_stats['questions_added']} questions added")
        print(f"   • {trainer.training_stats['concepts_enhanced']} concepts enhanced")
        print(f"   • {trainer.training_stats['domains_expanded']} domains expanded")
        
        print(f"\n🚀 Next Steps:")
        print(f"   1. Test the trained system: python test_ai_trained_system.py")
        print(f"   2. Use in production: streamlit run crisp_dm_app.py")
        print('='*80)
    
    except FileNotFoundError:
        print(f"\n❌ AI training data not found: {ai_data_file}")
        print(f"\n🚀 Generate it first:")
        print(f"   python ai_training_generator.py")
    
    except Exception as e:
        print(f"\n❌ Error: {e}")


if __name__ == "__main__":
    main()
